-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(100-IF(C.DISCOUNT_RATE IS NULL, 0, C.DISCOUNT_RATE))/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE 1 = 1
AND A.CAR_TYPE IN ('세단', 'SUV')
AND C.DURATION_TYPE LIKE '30일 이상'
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
AND MAX(B.END_DATE) <= '2022-11-01'
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;